; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
; upload_port = COM3
; monitor_port = COM4
; monitor_speed = 115200
build_flags =
    -include include/usb_descriptors_override.h
lib_deps =
    Bounce2
    https://github.com/mheironimus/arduinojoysticklibrary.git
    arduino-libraries/Keyboard
